name: 'Example'

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  call-workflow-graph:
    uses: ./.github/workflows/graph.yml
    strategy:
      matrix:
        path: [example/count]
    with:
      ref: ${{ github.head_ref }}
      branch: ${{ github.head_ref }}
      terraform-path: ${{ matrix.path }}
    secrets: inherit
