name: 'Example'

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: semnil/tfdiagrams:1.9.2

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Add bash command (for ad-m/github-push-action)
        if: ${{ success() }}
        run: |
          apk add bash
      - name: Git config
        run: |
          git config --global user.name "github actions"
          git config --global user.email "1051877+semnil@users.noreply.github.com"
          git config --global --add safe.directory /__w/tfdiagrams/tfdiagrams

      - name: Generate graph
        run: |
          cd example/count && terraform init && terraform graph | tfdot -o../../graph.png

      - name: Graph update status
        run: |
          git commit -a -m "Update graph by tfdiagrams"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}
