name: 'Example'

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: semnil/tfdiagrams:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Add bash command (for ad-m/github-push-action)
        if: ${{ success() }}
        run: |
          apk add bash
      - name: Git config
        run: |
          git config --global user.name "github actions"
          git config --global user.email "1051877+semnil@users.noreply.github.com"
          git config --global --add safe.directory /__w/tfdiagrams/tfdiagrams

      - name: Generate graph
        run: |
          cd example/count && terraform init && terraform graph | tfdot -o../../graph.png

      - name: Graph update status
        run: |
          git add -A
          git diff --cached --exit-code --quiet || echo "##[set-output name=update;]$(echo true)"
        id: graph_status
      - name: Commit files
        if: ${{ steps.graph_status.outputs.update == 'true' }}
        run: |
          git commit -m "Update graph by tfdiagrams" && echo "##[set-output name=commit;]$(echo true)"
        id: git_commit
      - name: Push changes
        if: ${{ steps.git_commit.outputs.commit == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
